### ISSUE TITLE
"$apply already in progress" when using events

### ISSUE THREAD

**Issue by ogazioglu** [develersrl/angular-flot#30]
This event binding method doesn't work in all cases. Anyway people say that the "scope.$apply" is an anti-pattern.
You should inject $timeout to directive and change all "scope.$apply" to "$timeout" to fix it and make worked in all cases.

This is the error :

Error: [$rootScope:inprog] $apply already in progress
http://errors.angularjs.org/1.3.14/$rootScope/inprog?p0=%24apply
    at http://localhost:54147/Scripts/angular.js:63:12
    at beginPhase (http://localhost:54147/Scripts/angular.js:14755:15)
    at Scope.$apply (http://localhost:54147/Scripts/angular.js:14499:11)
    at HTMLDivElement.onPlotSelected (http://localhost:54147/Scripts/angular-flot.js?v=0.0.14:72:15)
    at HTMLDivElement.n.event.dispatch (http://localhost:54147/Scripts/jquery-2.1.4.min.js:3:6466)
    at HTMLDivElement.r.handle (http://localhost:54147/Scripts/jquery-2.1.4.min.js:3:3241)
    at Object.n.event.trigger (http://localhost:54147/Scripts/jquery-2.1.4.min.js:3:5574)
    at HTMLDivElement.<anonymous> (http://localhost:54147/Scripts/jquery-2.1.4.min.js:3:11542)
    at Function.n.extend.each (http://localhost:54147/Scripts/jquery-2.1.4.min.js:2:2882)
    at n.fn.n.each (http://localhost:54147/Scripts/jquery-2.1.4.min.js:2:847) undefined

**Comment by lvillani** [comment]
You mean a zero-second $timeout ?

**Comment by ogazioglu** [comment]
Yes, like that:

     plotArea.on('plotclick', function onPlotClick(event, pos, item) {
                $timeout(function onApplyPlotClick() {
                    scope.onPlotClick({
                        event: event,
                        pos: pos,
                        item: item
                    });
                });
            });

And injections should be this format:

     angular.module('angular-flot', []).directive('flot', ['$timeout', function ($timeout) {

It works, tested...

**Comment by lvillani** [comment]
Just published v0.0.15. Can you give it a shot?

**Comment by ogazioglu** [comment]
Ok, it works.
